package it.pagopa.pn.deliverypush.middleware.queue.consumer.router;

// Dovranno essere censiti qui tutti i tipi di eventi supportati dal router.
public enum SupportedEventType {
    NEW_NOTIFICATION,
    START_RECIPIENT_WORKFLOW,
    NOTIFICATION_PAID,
    NOTIFICATION_VIEWED,
    SEND_IO_MESSAGE_REQUEST,
    NOTIFICATION_VALIDATION,
    NOTIFICATION_REFUSED,
    SCHEDULE_RECEIVED_LEGALFACT_GENERATION,
    NOTIFICATION_CANCELLATION,
    CHECK_ATTACHMENT_RETENTION,
    CHOOSE_DELIVERY_MODE,
    ANALOG_WORKFLOW,
    DIGITAL_WORKFLOW_NEXT_ACTION,
    DIGITAL_WORKFLOW_NEXT_EXECUTE_ACTION,
    DIGITAL_WORKFLOW_NO_RESPONSE_TIMEOUT_ACTION,
    DIGITAL_WORKFLOW_RETRY_ACTION,
    SEND_DIGITAL_FINAL_STATUS_RESPONSE,
    REFINEMENT_NOTIFICATION,
    DOCUMENT_CREATION_RESPONSE,
    POST_ACCEPTED_PROCESSING_COMPLETED,
    SEND_ANALOG_FINAL_STATUS_RESPONSE
}
