# Application
spring.application.name=PN-DELIVERY-PUSH
logging.config=classpath:logback-base.xml
cors.allowed.domains=http://localhost:8090,http://localhost:8091

# External services
pn.delivery-push.action-manager-base-url=http://localhost:8090
pn.delivery-push.data-vault-base-url=http://localhost:8084
pn.delivery-push.delivery-base-url=http://localhost:8080
pn.delivery-push.external-registry-base-url=http://localhost:8087
pn.delivery-push.mandate-base-url=http://localhost:8086
pn.delivery-push.paper-tracker-client-base-url=http://localhost:8090
pn.delivery-push.safe-storage-base-url=http://localhost:8120
pn.delivery-push.templates-engine-base-url=http://localhost:8090
pn.delivery-push.timeline-client-base-url=http://localhost:8091

#DB Table
pn.delivery-push.document-creation-request-dao.table-name=DocumentCreationRequest
pn.delivery-push.failed-notification-dao.table-name=PaperNotificationFailed
pn.delivery-push.notification-reworks-dao.table-name=NotificationReworks

# Middleware
pn.middleware.impl.document-creation=dynamo
pn.middleware.impl.failed-notification=dynamo
pn.middleware.init.aws=true
pn.middleware.init.kafka=false

# Safe Storage
pn.delivery-push.safe-storage-cx-id=pn-delivery-push
pn.delivery-push.safe-storage-cx-id-updatemetadata=pn-delivery

# Client certificates
cert.clientCertificatePem=${CLIENT_CERTIFICATE_PEM:}
cert.clientKeyPem=${CLIENT_KEY_PEM:}
cert.serverCertificatesPem=${SERVER_CERTIFICATES_PEM:}

# Cache
pn.cache.enabled=true
pn.cache.cacheNames=aooSenderIdCache(100000)

# Notification parameters
pn.delivery-push.additional-langs-enabled=false
pn.delivery-push.document-number-of-pages-tag-key=document_number_of_pages
pn.delivery-push.pagopa-notification-base-cost=100
pn.delivery-push.pago-pa-notification-base-cost=100
pn.delivery-push.pago-pa-notification-fee=100
pn.delivery-push.pago-pa-notification-vat=22

# Attachment retention in days after viewing or expiry
pn.delivery-push.retention-attachment-days-after-refinement=120

# Monitoring
management.endpoints.web.exposure.include=health,metrics,loggers

# AWS specific configurations
aws.bucketName=local-doc-bucket
aws.region-code=us-east-1
aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.endpoint-url=http://localhost:4566