AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  PhysicalPersonPortalUrl:
    Type: String
    Description: 'Url del portale della Persona Fisica/Giuridica?? da inserire degli AAR'

  AddressBookUrl:
    Type: String
    Description: 'The URL of address book mock service'

  WebhookScanInterval:
    Type: String
    Description: 'Time interval between two webhook-scans every scan send notifications
                  update to Public Administration'

  WebhookMaxLength:
    Type: String
    Description: 'Max elements quantity for each webhook call'

  PecSecondAttemptWaitTime:
    Type: String
    Description: 'Time to wait from first to second pec attempt. See https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-conversion-duration'

  RecipientTimeoutDelayDigital:
    Type: String
    Description: 'refinement time for digital workflow. See https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-conversion-duration'

  RecipientTimeoutDelayAnalog:
    Type: String
    Description: 'refinement time for analog successful workflow. See https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-conversion-duration'

  RefinementTimeCompletelyUnreachable:
    Type: String
    Description: 'refinement time for analog failed workflow. See https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-conversion-duration'

  ApiDnsName:
    Type: String
    Description: 'The DNS name used for B2B rest API.'

  WebApiDnsName:
    Type: String
    Description: 'The DNS name used for WEB rest API.'

  IoApiDnsName:
    Type: String
    Description: 'The DNS name used for IO rest API.'

  CorsAllowedDomains:
    Type: String
    Description: 'Comma separated list of domains allowed to make cross origin request'

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  DeliveryPushInputsQueueName:
    Type: String
    Description: 'Queue to pull for inputs event'
  DeliveryPushInputsQueueARN:
    Type: String
    Description: 'Queue to pull for inputs event'

  ExternalChannelsInputsQueueName:
    Type: String
    Description: 'Send external-channel messages to this Queue'
  ExternalChannelsInputsQueueARN:
    Type: String
    Description: 'Send external-channel messages to this Queue'

  ExternalChannelsOutputsQueueName:
    Type: String
    Description: 'Pull external-channel messages from this Queue'
  ExternalChannelsOutputsQueueARN:
    Type: String
    Description: 'Pull external-channel messages from this Queue'

  ScheduledActionsQueueName:
    Type: String
    Description: 'Send and pull ready-to-do actions th this queue'
  ScheduledActionsQueueARN:
    Type: String
    Description: 'Send and pull ready-to-do actions th this queue'

  DoneActionsQueueName:
    Type: String
    Description: 'Send done actions to this queue read by webhook'
  DoneActionsQueueARN:
    Type: String
    Description: 'Send done actions to this queue read by webhook'

  LegalFactsBucketName:
    Type: String
    Description: 'Where to write documents files'

  LegalFactsBucketArn:
    Type: String
    Description: 'Where to write documents files'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'

  TimelinesDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing timelines

  TimelinesDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing timelines

  PaperNotificationFailedDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing unreacheble notifications recipients

  PaperNotificationFailedDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing unreacheble notifications recipients

  ActionDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing

  ActionDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing

  FutureActionDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing

  FutureActionDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing

  LastPollForFutureActionDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing

  LastPollForFutureActionDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing

  PnDeliveryPushShedLockDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing

  PnDeliveryPushShedLockDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing


  PnDeliveryPushWebhookStreamsTableName:
    Type: String
    Description: Name of dynamodb table containing

  PnDeliveryPushWebhookStreamsTableArn:
    Type: String
    Description: ARN of dynamodb table containing

  PnDeliveryPushWebhookEventsTableName:
    Type: String
    Description: Name of dynamodb table containing

  PnDeliveryPushWebhookEventsTableArn:
    Type: String
    Description: ARN of dynamodb table containing

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  ExternalChannelBaseUrl:
    Type: String
    Description: url base di external channel

  SandboxSafeStorageBaseUrl:
    Type: String
    Description: url base di safe storage

Resources:

  # PN-Delivery-push microservice
  DeliveryPushMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-delivery-push'
        CpuValue: 1024
        MemoryAmount: 2GB
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGIONCODE=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'AWS_BUCKETNAME=${LegalFactsBucketName}'
        ContainerEnvEntry3: !Sub 'PN_CLIENTS_ADDRESSBOOKBASEURL=${AddressBookUrl}'
        ContainerEnvEntry4: !Sub 'PN_DELIVERYPUSH_EXTERNALCHANNELBASEURL=${ExternalChannelBaseUrl}'
        ContainerEnvEntry5: !Sub 'PN_DELIVERYPUSH_TOPICS_NEWNOTIFICATIONS=${DeliveryPushInputsQueueName}'
        ContainerEnvEntry6: !Sub 'PN_DELIVERYPUSH_TOPICS_TOEXTERNALCHANNELPEC=${ExternalChannelsInputsQueueName}'
        ContainerEnvEntry7: !Sub 'PN_DELIVERYPUSH_TOPICS_TOEXTERNALCHANNELEMAIL=${ExternalChannelsInputsQueueName}'
        ContainerEnvEntry8: !Sub 'PN_DELIVERYPUSH_TOPICS_TOEXTERNALCHANNELPAPER=${ExternalChannelsInputsQueueName}'
        ContainerEnvEntry9: !Sub 'PN_DELIVERYPUSH_TOPICS_FROMEXTERNALCHANNEL=${ExternalChannelsOutputsQueueName}'
        ContainerEnvEntry10: !Sub 'PN_DELIVERYPUSH_TOPICS_SCHEDULEDACTIONS=${ScheduledActionsQueueName}'
        ContainerEnvEntry11: !Sub 'PN_DELIVERYPUSH_TOPICS_EXECUTEDACTIONS=${DoneActionsQueueName}'
        ContainerEnvEntry12: !Sub 'PN_DELIVERYPUSH_WEBHOOK_SCHEDULEINTERVAL=${WebhookScanInterval}'
        ContainerEnvEntry13: !Sub 'PN_DELIVERYPUSH_WEBHOOK_MAXLENGTH=${WebhookMaxLength}'
        ContainerEnvEntry14: !Sub 'PN_DELIVERYPUSH_WEBAPP_DIRECTACCESSURLTEMPLATE=${PhysicalPersonPortalUrl}/direct_access.html?token=%s'
        ContainerEnvEntry15: !Sub 'PN_DELIVERYPUSH_TIMEPARAMS_SECONDATTEMPTWAITINGTIME=${PecSecondAttemptWaitTime}'
        ContainerEnvEntry16: !Sub 'PN_DELIVERYPUSH_TIMEPARAMS_RECIPIENTVIEWMAXTIMEFORDIGITAL=${RecipientTimeoutDelayDigital}'
        ContainerEnvEntry17: !Sub 'PN_DELIVERYPUSH_TIMEPARAMS_RECIPIENTVIEWMAXTIMEFORANALOG=${RecipientTimeoutDelayAnalog}'
        ContainerEnvEntry18: !Sub 'PN_DELIVERYPUSH_TIMEPARAMS_REFINEMENTTIMEFORCOMPLETELYUNREACHABLE=${RefinementTimeCompletelyUnreachable}'
        ContainerEnvEntry19: !Sub 'PN_DELIVERYPUSH_DATAVAULTBASEURL=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry20: !Sub 'PN_DELIVERYPUSH_USERATTRIBUTESBASEURL=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry21: !Sub 'PN_DELIVERYPUSH_SAFESTORAGEBASEURL=${SandboxSafeStorageBaseUrl}'
        ContainerEnvEntry22: !Sub 'SPRING_CLOUD_FUNCTIONROUTER_QUEUES_LIST=${DeliveryPushInputsQueueName},${ExternalChannelsOutputsQueueName},${ScheduledActionsQueueName}'
        ContainerEnvEntry23: !Sub 'PN_DELIVERYPUSH_DELIVERYBASEURL=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry24: !Sub 'CORS_ALLOWED_DOMAINS=${CorsAllowedDomains}'
        ContainerEnvEntry25: !Sub 'PN_DELIVERYPUSH_TIMELINEDAO_TABLENAME=${TimelinesDynamoTableName}'
        ContainerEnvEntry26: !Sub 'PN_DELIVERYPUSH_FAILEDNOTIFICATIONDAO_TABLENAME=${PaperNotificationFailedDynamoTableName}'
        ContainerEnvEntry27: !Sub 'PN_DELIVERYPUSH_ACTIONDAO_TABLENAME=${ActionDynamoTableName}'
        ContainerEnvEntry28: !Sub 'PN_DELIVERYPUSH_FUTUREACTIONDAO_TABLENAME=${FutureActionDynamoTableName}'
        ContainerEnvEntry29: !Sub 'PN_DELIVERYPUSH_LASTPOLLFORFUTUREACTIONDAO_TABLENAME=${LastPollForFutureActionDynamoTableName}'
        ContainerEnvEntry30: !Sub 'PN_DELIVERYPUSH_LASTPOLLFORFUTUREACTIONDAO_LOCKTABLENAME=${PnDeliveryPushShedLockDynamoTableName}'
        ContainerEnvEntry31: !Sub 'PN_DELIVERYPUSH_WEBHOOKDAO_EVENTSTABLENAME=${PnDeliveryPushWebhookEventsTableName}'
        ContainerEnvEntry32: !Sub 'PN_DELIVERYPUSH_WEBHOOKDAO_STREAMSTABLENAME=${PnDeliveryPushWebhookStreamsTableName}'
        ContainerEnvEntry33: !Sub 'PN_DELIVERYPUSH_MANDATEBASEURL=http://${ApplicationLoadBalancerDomain}:8080'
        MappedPaths: '/delivery-push/*,/delivery-push-private/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref SubnetsIds
        VpcId: !Ref VpcId
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber

  # Grant operational rights to PN-Delivery-push microservice microservice
  DeliveryPushMicroserviceTaskPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ProjectName}-delivery-push-CustomTaskPolicy'
      Roles:
        - !GetAtt DeliveryPushMicroservice.Outputs.TaskRoleName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sqs:ChangeMessageVisibility
              - sqs:ChangeMessageVisibilityBatch
              - sqs:DeleteMessage
              - sqs:DeleteMessageBatch
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:SendMessage
              - sqs:SendMessageBatch
            Resource:
              - !Ref DeliveryPushInputsQueueARN
              - !Ref ExternalChannelsInputsQueueARN
              - !Ref ExternalChannelsOutputsQueueARN
              - !Ref ScheduledActionsQueueARN
              - !Ref DoneActionsQueueARN
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:GetObjectLegalHold
              - s3:GetObjectRetention
              - s3:GetObjectTagging
              - s3:GetObjectVersion
              - s3:GetObjectVersionAcl
              - s3:GetObjectVersionTagging
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Resource:
              - !Sub '${LegalFactsBucketArn}/*'
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Ref LegalFactsBucketArn
          - Effect: Allow
            Action:
              - cassandra:Modify
              - cassandra:Select
            Resource:
              - !Sub "arn:aws:cassandra:*:${AWS::AccountId}:/keyspace/*/table/*"
          - Effect: Allow
            Action:
              - 'dynamodb:GetItem'
              - 'dynamodb:Query'
              - 'dynamodb:PutItem'
            Resource:
              - !Sub "${TimelinesDynamoTableArn}"
              - !Sub "${PaperNotificationFailedDynamoTableArn}"
              - !Sub "${ActionDynamoTableArn}"
          - Effect: Allow
            Action:
              - 'dynamodb:GetItem'
              - 'dynamodb:Query'
              - 'dynamodb:PutItem'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:UpdateItem'
            Resource:
              - !Sub "${FutureActionDynamoTableArn}"
              - !Sub "${LastPollForFutureActionDynamoTableArn}"
              - !Sub "${PnDeliveryPushShedLockDynamoTableArn}"
              - !Sub "${PnDeliveryPushWebhookStreamsTableArn}"
              - !Sub "${PnDeliveryPushWebhookEventsTableArn}"

  # Expose PN-Delivery-push microservice public API with API-GW for B2B usage
  DeliveryPushMicroservicePublicAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-delivery-push'
        IntendedUsage: B2B
        DnsName: !Ref ApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'delivery-push'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain

  # Expose PN-Delivery-push microservice public API with API-GW for WEB usage
  DeliveryPushMicroservicePublicWebAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-delivery-push'
        IntendedUsage: WEB
        DnsName: !Ref WebApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'delivery-push'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain

  # Expose PN-Delivery-push microservice public API with API-GW for IO usage
  # DeliveryPushMicroservicePublicIoAPI:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
  #     Parameters:
  #       MicroServiceUniqueName: !Sub '${ProjectName}-delivery-push'
  #       IntendedUsage: IO
  #       DnsName: !Ref IoApiDnsName
  #       ProjectName: !Ref ProjectName
  #       ServiceApiPath: 'delivery-push'
  #       NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
  #       ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
