AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  PhysicalPersonPortalUrl:
    Type: String
    Description: 'Url del portale della Persona Fisica/Giuridica?? da inserire degli AAR'

  AddressBookUrl:
    Type: String
    Description: 'The URL of address book mock service'

  WebhookScanInterval:
    Type: String
    Description: 'Time interval between two webhook-scans every scan send notifications
                  update to Public Administration'

  WebhookMaxLength:
    Type: String
    Description: 'Max elements quantity for each webhook call'

  WaitingForReadCourtesyMessage:
    Type: String
    Description: 'Time to wait before starting the analog workflow. See https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-conversion-duration'

  SecondNotificationWorkflowWaitingTime:
    Type: String
    Description: 'Time to wait from first to second pec attempt. See https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-conversion-duration'
  
  SchedulingDaysSuccessDigitalRefinement:
    Type: String
    Description: 'refinement time for digital workflow success. See https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-conversion-duration'

  SchedulingDaysFailureDigitalRefinement:
    Type: String
    Description: 'refinement time for digital workflow failure. See https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-conversion-duration'

  SchedulingDaysSuccessAnalogRefinement:
    Type: String
    Description: 'refinement time for Analog workflow success. See https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-conversion-duration'

  SchedulingDaysFailureAnalogRefinement:
    Type: String
    Description: 'refinement time for Analog workflow failure. See https://docs.spring.io/spring-boot/docs/2.1.12.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-conversion-duration'
  
  ApiDnsName:
    Type: String
    Description: 'The DNS name used for B2B rest API.'

  WebApiDnsName:
    Type: String
    Description: 'The DNS name used for WEB rest API.'

  IoApiDnsName:
    Type: String
    Description: 'The DNS name used for IO rest API.'

  CorsAllowedDomains:
    Type: String
    Description: 'Comma separated list of domains allowed to make cross origin request'

  ContainerImageUri:
    Type: String
    Description: 'Exact container image URI with full repository and image digest'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  DeliveryPushInputsQueueName:
    Type: String
    Description: 'Queue to pull for inputs event'
    
  DeliveryPushInputsQueueARN:
    Type: String
    Description: 'Queue to pull for inputs event'

  ExternalChannelsInputsQueueName:
    Type: String
    Description: 'Send external-channel messages to this Queue'
    
  ExternalChannelsInputsQueueARN:
    Type: String
    Description: 'Send external-channel messages to this Queue'

  ExternalChannelsOutputsQueueName:
    Type: String
    Description: 'Pull external-channel messages from this Queue'
    
  ExternalChannelsOutputsQueueARN:
    Type: String
    Description: 'Pull external-channel messages from this Queue'

  ScheduledActionsQueueName:
    Type: String
    Description: 'Send and pull ready-to-do actions th this queue'
    
  ScheduledActionsQueueARN:
    Type: String
    Description: 'Send and pull ready-to-do actions th this queue'

  DoneActionsQueueName:
    Type: String
    Description: 'Send done actions to this queue read by webhook'
    
  DoneActionsQueueARN:
    Type: String
    Description: 'Send done actions to this queue read by webhook'

  ECSClusterName:
    Type: String
    Description: 'The name of the ECS cluster where the microservice is going to be deployed'

  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'
  
  EcsDefaultSecurityGroup:
    Type: String
    Description: 'Default security group required by infrastructure'

  ApplicationLoadBalancerListenerArn:
    Type: String
    Description: 'Load balancer listener where HTTP endpoints is going to be registered'

  ApplicationLoadBalancerDomain:
    Type: String
    Description: 'Base URL of the load balancer where the service is going to be reachable'

  NetworkLoadBalancerLink:
    Type: String
    Description: 'network load balancer link for API-GW'

  TimelinesDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing timelines

  TimelinesDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing timelines

  PaperNotificationFailedDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing unreacheble notifications recipients

  PaperNotificationFailedDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing unreacheble notifications recipients

  ActionDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing

  ActionDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing

  FutureActionDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing

  FutureActionDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing

  LastPollForFutureActionDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing

  LastPollForFutureActionDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing

  PnDeliveryPushShedLockDynamoTableName:
    Type: String
    Description: Name of dynamodb table containing

  PnDeliveryPushShedLockDynamoTableArn:
    Type: String
    Description: ARN of dynamodb table containing

  PnDeliveryPushWebhookStreamsTableName:
    Type: String
    Description: Name of dynamodb table containing

  PnDeliveryPushWebhookStreamsTableArn:
    Type: String
    Description: ARN of dynamodb table containing

  PnDeliveryPushWebhookEventsTableName:
    Type: String
    Description: Name of dynamodb table containing

  PnDeliveryPushWebhookEventsTableArn:
    Type: String
    Description: ARN of dynamodb table containing

  AlarmSNSTopicArn:
    Type: String
    Description: ARN of alarm topic

  ExternalChannelBaseUrl:
    Type: String
    Description: url base di external channel

  SandboxSafeStorageBaseUrl:
    Type: String
    Description: url base di safe storage
  
  LogsBucketName:
    Type: String
    Description: Bucket name where the logs must be exported
    
  LogsExporterRoleArn:
    Type: String
    Description: ARN of the role used to write to external logs bucket
  
  TimelineCdcKinesisStreamArn:
    Type: String
    Description: kinesis stream Arn for timeline dynamo table
  
  TimelineCdcKinesisKeyArn:
    Type: String
    Description: KMS key arn for timeline stream decryption

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  PnDeliveryPushPaperMessageNotHandled:
    Type: String
    Description: feature flag disabilitazione invio messaggi cartacei
  
Resources:

  # PN-Delivery-push microservice
  DeliveryPushMicroservice:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/ecs-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-delivery-push'
        CpuValue: 1024
        MemoryAmount: 2GB
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
        ContainerImageURI: !Sub '${ContainerImageUri}'
        ContainerEnvEntry1: !Sub 'AWS_REGIONCODE=${AWS::Region}'
        ContainerEnvEntry2: !Sub 'PN_DELIVERYPUSH_TOPICS_NEWNOTIFICATIONS=${DeliveryPushInputsQueueName}'
        ContainerEnvEntry3: !Sub 'PN_DELIVERYPUSH_TOPICS_TOEXTERNALCHANNELPEC=${ExternalChannelsInputsQueueName}'
        ContainerEnvEntry4: !Sub 'PN_DELIVERYPUSH_TOPICS_TOEXTERNALCHANNELEMAIL=${ExternalChannelsInputsQueueName}'
        ContainerEnvEntry5: !Sub 'PN_DELIVERYPUSH_TOPICS_TOEXTERNALCHANNELPAPER=${ExternalChannelsInputsQueueName}'
        ContainerEnvEntry6: !Sub 'PN_DELIVERYPUSH_TOPICS_FROMEXTERNALCHANNEL=${ExternalChannelsOutputsQueueName}'
        ContainerEnvEntry7: !Sub 'PN_DELIVERYPUSH_TOPICS_SCHEDULEDACTIONS=${ScheduledActionsQueueName}'
        ContainerEnvEntry8: !Sub 'PN_DELIVERYPUSH_TOPICS_EXECUTEDACTIONS=${DoneActionsQueueName}'
        ContainerEnvEntry9: !Sub 'PN_DELIVERYPUSH_WEBHOOK_SCHEDULEINTERVAL=${WebhookScanInterval}'
        ContainerEnvEntry10: !Sub 'PN_DELIVERYPUSH_WEBHOOK_MAXLENGTH=${WebhookMaxLength}'
        # ContainerEnvEntry11: !Sub 'PN_DELIVERYPUSH_WEBAPP_DIRECTACCESSURLTEMPLATE=${PhysicalPersonPortalUrl}/direct_access.html?token=%s'
        ContainerEnvEntry11: !Sub 'PN_DELIVERYPUSH_WEBAPP_DIRECTACCESSURLTEMPLATE=${PhysicalPersonPortalUrl}'
        ContainerEnvEntry12: !Sub 'PN_DELIVERYPUSH_WEBHOOKDAO_EVENTSTABLENAME=${PnDeliveryPushWebhookEventsTableName}'
        ContainerEnvEntry13: !Sub 'PN_DELIVERYPUSH_WEBHOOKDAO_STREAMSTABLENAME=${PnDeliveryPushWebhookStreamsTableName}'
        ContainerEnvEntry14: !Sub 'PN_DELIVERYPUSH_TIMEPARAMS_WAITINGFORREADCOURTESYMESSAGE=${WaitingForReadCourtesyMessage}'
        ContainerEnvEntry15: !Sub 'PN_DELIVERYPUSH_TIMEPARAMS_SECONDNOTIFICATIONWORKFLOWWAITINGTIME=${SecondNotificationWorkflowWaitingTime}'
        ContainerEnvEntry16: !Sub 'PN_DELIVERYPUSH_TIMEPARAMS_SCHEDULINGDAYSSUCCESSDIGITALREFINEMENT=${SchedulingDaysSuccessDigitalRefinement}'
        ContainerEnvEntry17: !Sub 'PN_DELIVERYPUSH_TIMEPARAMS_SCHEDULINGDAYSFAILUREDIGITALREFINEMENT=${SchedulingDaysFailureDigitalRefinement}'
        ContainerEnvEntry18: !Sub 'PN_DELIVERYPUSH_TIMEPARAMS_SCHEDULINGDAYSSUCCESSANALOGREFINEMENT=${SchedulingDaysSuccessAnalogRefinement}'
        ContainerEnvEntry19: !Sub 'PN_DELIVERYPUSH_TIMEPARAMS_SCHEDULINGDAYFAILUREANALOGREFINEMENT=${SchedulingDaysFailureAnalogRefinement}'
        ContainerEnvEntry20: !Sub 'PN_CLIENTS_ADDRESSBOOKBASEURL=${AddressBookUrl}'
        ContainerEnvEntry21: !Sub 'PN_DELIVERYPUSH_EXTERNALCHANNELBASEURL=${ExternalChannelBaseUrl}'
        ContainerEnvEntry22: 'PN_DELIVERYPUSH_DATAVAULTBASEURL=http://alb.confidential.pn.internal:8080'
        ContainerEnvEntry23: !Sub 'PN_DELIVERYPUSH_USERATTRIBUTESBASEURL=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry24: !Sub 'PN_DELIVERYPUSH_SAFESTORAGEBASEURL=${SandboxSafeStorageBaseUrl}'
        ContainerEnvEntry25: !Sub 'PN_DELIVERYPUSH_DELIVERYBASEURL=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry26: !Sub 'PN_DELIVERYPUSH_MANDATEBASEURL=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry27: !Sub 'PN_DELIVERYPUSH_EXTERNALREGISTRYBASEURL=http://${ApplicationLoadBalancerDomain}:8080'
        ContainerEnvEntry28: !Sub 'SPRING_CLOUD_FUNCTIONROUTER_QUEUES_LIST=${DeliveryPushInputsQueueName},${ExternalChannelsOutputsQueueName},${ScheduledActionsQueueName}'
        ContainerEnvEntry29: !Sub 'CORS_ALLOWED_DOMAINS=${CorsAllowedDomains}'
        ContainerEnvEntry30: !Sub 'PN_DELIVERYPUSH_TIMELINEDAO_TABLENAME=${TimelinesDynamoTableName}'
        ContainerEnvEntry31: !Sub 'PN_DELIVERYPUSH_FAILEDNOTIFICATIONDAO_TABLENAME=${PaperNotificationFailedDynamoTableName}'
        ContainerEnvEntry32: !Sub 'PN_DELIVERYPUSH_ACTIONDAO_TABLENAME=${ActionDynamoTableName}'
        ContainerEnvEntry33: !Sub 'PN_DELIVERYPUSH_FUTUREACTIONDAO_TABLENAME=${FutureActionDynamoTableName}'
        ContainerEnvEntry34: !Sub 'PN_DELIVERYPUSH_LASTPOLLFORFUTUREACTIONDAO_TABLENAME=${LastPollForFutureActionDynamoTableName}'
        ContainerEnvEntry35: !Sub 'PN_DELIVERYPUSH_LASTPOLLFORFUTUREACTIONDAO_LOCKTABLENAME=${PnDeliveryPushShedLockDynamoTableName}'
        ContainerEnvEntry36: !Sub 'PN_DELIVERYPUSH_PAPERMESSAGENOTHANDLED=${PnDeliveryPushPaperMessageNotHandled}'
        ContainerEnvEntry37: !Sub 'PN_DELIVERYPUSH_WEBAPP_FAQURLTEMPLATE=${PhysicalPersonPortalUrl}/faq.html'
        JavaToolOptions: '-Dreactor.netty.ioWorkerCount=50'
        MappedPaths: '/delivery-push/*,/delivery-push-private/*,/delivery-progresses/*'
        ECSClusterName: !Ref ECSClusterName
        Subnets: !Ref SubnetsIds
        VpcId: !Ref VpcId
        EcsDefaultSecurityGroup: !Ref EcsDefaultSecurityGroup
        LoadBalancerListenerArn: !Ref ApplicationLoadBalancerListenerArn
        LoadbalancerRulePriority: !Ref MicroserviceNumber

  # Grant operational rights to PN-Delivery-push microservice microservice
  DeliveryPushMicroserviceTaskPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ProjectName}-delivery-push-CustomTaskPolicy'
      Roles:
        - !GetAtt DeliveryPushMicroservice.Outputs.TaskRoleName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sqs:ChangeMessageVisibility
              - sqs:ChangeMessageVisibilityBatch
              - sqs:DeleteMessage
              - sqs:DeleteMessageBatch
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:SendMessage
              - sqs:SendMessageBatch
            Resource:
              - !Ref DeliveryPushInputsQueueARN
              - !Ref ExternalChannelsInputsQueueARN
              - !Ref ExternalChannelsOutputsQueueARN
              - !Ref ScheduledActionsQueueARN
              - !Ref DoneActionsQueueARN
          - Effect: Allow
            Action:
              - 'dynamodb:GetItem'
              - 'dynamodb:Query'
              - 'dynamodb:PutItem'
            Resource:
              - !Sub "${TimelinesDynamoTableArn}"
              - !Sub "${PaperNotificationFailedDynamoTableArn}"
              - !Sub "${ActionDynamoTableArn}"
          - Effect: Allow
            Action:
              - 'dynamodb:GetItem'
              - 'dynamodb:Query'
              - 'dynamodb:PutItem'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:UpdateItem'
            Resource:
              - !Sub "${FutureActionDynamoTableArn}"
              - !Sub "${LastPollForFutureActionDynamoTableArn}"
              - !Sub "${PnDeliveryPushShedLockDynamoTableArn}"
              - !Sub "${PnDeliveryPushWebhookStreamsTableArn}"
              - !Sub "${PnDeliveryPushWebhookEventsTableArn}"

  # Expose PN-Delivery-push microservice public API with API-GW for B2B usage
  DeliveryPushMicroservicePublicAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-delivery-push'
        IntendedUsage: B2B
        DnsName: !Ref ApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'delivery-push'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
  DeliveryPushMicroservicePublicApiWaf:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
      Parameters:
        WAFName: !Sub '${ProjectName}-delivery-push-b2b'
        WAFRuleVendors: "AWS,AWS,AWS"
        WAFRuleNames: "AWSManagedRulesKnownBadInputsRuleSet,AWSManagedRulesAdminProtectionRuleSet,AWSManagedRulesCommonRuleSet"
        APIGatewayARN: !GetAtt DeliveryPushMicroservicePublicAPI.Outputs.APIGatewayARN

  # Expose PN-Delivery-progress microservice public API with API-GW for B2B usage
  DeliveryProgressMicroservicePublicAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-delivery-progress'
        IntendedUsage: B2B
        DnsName: !Ref ApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'delivery-progresses'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
  DeliveryProgressMicroservicePublicApiWaf:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
      Parameters:
        WAFName: !Sub '${ProjectName}-delivery-progress-b2b'
        WAFRuleVendors: "AWS,AWS,AWS"
        WAFRuleNames: "AWSManagedRulesKnownBadInputsRuleSet,AWSManagedRulesAdminProtectionRuleSet,AWSManagedRulesCommonRuleSet"
        APIGatewayARN: !GetAtt DeliveryProgressMicroservicePublicAPI.Outputs.APIGatewayARN

  # Expose PN-Delivery-push microservice public API with API-GW for WEB usage
  DeliveryPushMicroservicePublicWebAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-delivery-push'
        IntendedUsage: WEB
        DnsName: !Ref WebApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'delivery-push'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn
  DeliveryPushMicroservicePublicWebApiWaf:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-waf-acl.yaml"
      Parameters:
        WAFName: !Sub '${ProjectName}-delivery--push-web'
        WAFRuleVendors: "AWS, AWS, AWS, AWS"
        WAFRuleNames: "AWSManagedRulesBotControlRuleSet, AWSManagedRulesKnownBadInputsRuleSet, AWSManagedRulesAdminProtectionRuleSet, AWSManagedRulesCommonRuleSet"
        APIGatewayARN: !GetAtt DeliveryPushMicroservicePublicWebAPI.Outputs.APIGatewayARN


  # Expose PN-Delivery-push microservice public API with API-GW for IO usage
  DeliveryPushMicroservicePublicIoAPI:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/api-gw-expose-service.yaml"
      Parameters:
        MicroServiceUniqueName: !Sub '${ProjectName}-delivery-push'
        IntendedUsage: IO
        DnsName: !Ref IoApiDnsName
        ProjectName: !Ref ProjectName
        ServiceApiPath: 'delivery-push'
        NetworkLoadBalancerLink: !Ref NetworkLoadBalancerLink
        ApplicationLoadBalancerDomain: !Ref ApplicationLoadBalancerDomain
        AlarmSNSTopicArn: !Ref AlarmSNSTopicArn


