AWSTemplateFormatVersion: '2010-09-09'
Description: Actions storage

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: unused

  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'
  
  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'
  
  LogRetention:
    Type: Number
    Default: 14

Resources:

  # Legal Facts S3 Storage
  LegalFactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      # No default retention neither legal hold.
      # Can define retention period or legal hold when upload new object or version
      ObjectLockEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - "x-amz-version-id"

  # Internal queues
  ScheduledActionsQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain   
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_actions'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName        
        VisibilityTimeout: 60
        MaxReceiveCount: 10
        DelaySeconds: 1

  DoneActionsQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain   
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_actions_done'
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 60
        MaxReceiveCount: 10
        DelaySeconds: 1

  # internal queues DLQ
  NotificationCancellationActionInsertDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_cdc_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ: "false"
        QueueHasAlarm: "true"


  # internal queues DLQ
  WebhookEventManagerDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_webhook_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ: "false"
        QueueHasAlarm: "true"

  # Notification Timeline DynamoDB Table
  TimelinesTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain   
    Properties:
      TableName: !Sub '${ProjectName}-Timelines'
      AttributeDefinitions:
        - AttributeName: "iun"
          AttributeType: "S"
        - AttributeName: "timelineElementId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "iun"
          KeyType: "HASH"
        - AttributeName: "timelineElementId"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Failed Paper Notification
  PaperNotificationFailedTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain   
    Properties:
      TableName: !Sub '${ProjectName}-PaperNotificationFailed'
      AttributeDefinitions:
        - AttributeName: "recipientId"
          AttributeType: "S"
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "recipientId"
          KeyType: "HASH"
        - AttributeName: "iun"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
        
  # Action Table
  ActionTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain   
    Properties:
      TableName: !Sub '${ProjectName}-Action'
      AttributeDefinitions:
        - AttributeName: "actionId"
          AttributeType: "S"
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "actionId"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "iun-index"
          KeySchema:
            - AttributeName: "iun"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Future Action Table
  FutureActionTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain   
    Properties:
      TableName: !Sub '${ProjectName}-FutureAction'
      AttributeDefinitions:
        - AttributeName: "timeSlot"
          AttributeType: "S"
        - AttributeName: "actionId"
          AttributeType: "S"
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "timeSlot"
          KeyType: "HASH"
        - AttributeName: "actionId"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "iun-index"
          KeySchema:
            - AttributeName: "iun"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Last scheduled poll time
  LastPollForFutureActionTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain   
    Properties:
      TableName: !Sub '${ProjectName}-LastPollForFutureActionTable'
      AttributeDefinitions:
        - AttributeName: "lastPoolKey"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "lastPoolKey"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Shared lock handling table
  PnDeliveryPushShedLockTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain   
    Properties:
      TableName: !Sub '${ProjectName}-PnDeliveryPushShedLock'
      AttributeDefinitions:
        - AttributeName: "_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "_id"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # WebhookStreams table
  PnDeliveryPushWebhookStreamsTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain   
    Properties:
      TableName: !Sub '${ProjectName}-WebhookStreams'
      AttributeDefinitions:
        - AttributeName: "hashKey"
          AttributeType: "S"
        - AttributeName: "sortKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "hashKey"
          KeyType: "HASH"
        - AttributeName: "sortKey"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # WebhookEvents table
  PnDeliveryPushWebhookEventsTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain   
    Properties:
      TableName: !Sub '${ProjectName}-WebhookEvents'
      AttributeDefinitions:
        - AttributeName: "hashKey"
          AttributeType: "S"
        - AttributeName: "sortKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "hashKey"
          KeyType: "HASH"
        - AttributeName: "sortKey"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Safe storage table containing request
  DocumentCreationRequestTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain   
    Properties:
      TableName: !Sub '${ProjectName}-DocumentCreationRequestTable'
      AttributeDefinitions:
        - AttributeName: "key"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "key"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true


  TimelinesCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-TimelinesCounters'
      AttributeDefinitions:
        - AttributeName: "timelineElementId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "timelineElementId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true      

  PnDeliveryPushLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain 
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-delivery-push'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention

  NotificationCancellationActionInsertLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-notificationCancellationActionInsertLambda"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

  WebhookEventManagerLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-webhookEventManagerLambda"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

Outputs:

  # Scheduled Actions
  ScheduledActionsQueueName:
    Value: !GetAtt ScheduledActionsQueue.Outputs.QueueName
    Description: pn-delivery-push actions queue name
  ScheduledActionsQueueURL:
    Value: !GetAtt ScheduledActionsQueue.Outputs.QueueURL
    Description: pn-delivery-push actions queue URL
  ScheduledActionsQueueARN:
    Value: !GetAtt ScheduledActionsQueue.Outputs.QueueARN
    Description: pn-delivery-push actions queue ARN
  ScheduledActionsQueueAlarmARN:
    Value: !GetAtt ScheduledActionsQueue.Outputs.SqsDLQAlarmArn
    Description: pn-delivery-push actions queue dlq alarm queue 
  ScheduledActionsQueueAgeAlarmARN:
    Value: !GetAtt ScheduledActionsQueue.Outputs.SqsAgeAlarmArn
    Description: pn-delivery-push actions queue age alarm ARN

  # Already Done Actions
  DoneActionsQueueName:
    Value: !GetAtt DoneActionsQueue.Outputs.QueueName
    Description: pn-delivery-push actions done queue name
  DoneActionsQueueURL:
    Value: !GetAtt DoneActionsQueue.Outputs.QueueURL
    Description: pn-delivery-push actions done queue URL
  DoneActionsQueueARN:
    Value: !GetAtt DoneActionsQueue.Outputs.QueueARN
    Description: pn-delivery-push actions done queue ARN
  DoneActionsQueueAlarmARN:
    Value: !GetAtt DoneActionsQueue.Outputs.SqsDLQAlarmArn
    Description: pn-delivery-push actions done queue dlq alarm ARN
  DoneActionsQueueAgeAlarmARN:
    Value: !GetAtt DoneActionsQueue.Outputs.SqsAgeAlarmArn
    Description: pn-delivery-push actions done queue age alarm ARN

  # Dynamo tables
  TimelinesDynamoTableName:
    Description: Name of dynamodb table containing timelines
    Value: !Ref TimelinesTable
  TimelinesDynamoTableArn:
    Description: ARN of dynamodb table containing timelines
    Value: !Sub '${TimelinesTable.Arn}'

  PaperNotificationFailedDynamoTableName:
    Description: Name of dynamodb table containing unreacheble notifications recipients
    Value: !Ref PaperNotificationFailedTable
  PaperNotificationFailedDynamoTableArn:
    Description: ARN of dynamodb table containing unreacheble notifications recipients
    Value: !Sub '${PaperNotificationFailedTable.Arn}'

  ActionDynamoTableName:
    Description: Name of dynamodb table containing
    Value: !Ref ActionTable
  ActionDynamoTableArn:
    Description: ARN of dynamodb table containing
    Value: !Sub '${ActionTable.Arn}'

  FutureActionDynamoTableName:
    Description: Name of dynamodb table containing
    Value: !Ref FutureActionTable
  FutureActionDynamoTableArn:
    Description: ARN of dynamodb table containing
    Value: !Sub '${FutureActionTable.Arn}'

  LastPollForFutureActionDynamoTableName:
    Description: Name of dynamodb table containing
    Value: !Ref LastPollForFutureActionTable
  LastPollForFutureActionDynamoTableArn:
    Description: ARN of dynamodb table containing
    Value: !Sub '${LastPollForFutureActionTable.Arn}'

  PnDeliveryPushShedLockDynamoTableName:
    Description: Name of dynamodb table containing
    Value: !Ref PnDeliveryPushShedLockTable
  PnDeliveryPushShedLockDynamoTableArn:
    Description: ARN of dynamodb table containing
    Value: !Sub '${PnDeliveryPushShedLockTable.Arn}'


  PnDeliveryPushWebhookStreamsTableName:
    Description: Name of dynamodb table containing
    Value: !Ref PnDeliveryPushWebhookStreamsTable
  PnDeliveryPushWebhookStreamsTableArn:
    Description: ARN of dynamodb table containing
    Value: !Sub '${PnDeliveryPushWebhookStreamsTable.Arn}'

  PnDeliveryPushWebhookEventsTableName:
    Description: Name of dynamodb table containing
    Value: !Ref PnDeliveryPushWebhookEventsTable
  PnDeliveryPushWebhookEventsTableArn:
    Description: ARN of dynamodb table containing
    Value: !Sub '${PnDeliveryPushWebhookEventsTable.Arn}'

  DocumentCreationRequestTableName:
    Description: Name of dynamodb table containing Document creation request to storage
    Value: !Ref DocumentCreationRequestTable
  DocumentCreationRequestTableArn:
    Description: ARN of dynamodb table containing Document creation request to storage
    Value: !Sub '${DocumentCreationRequestTable.Arn}'


  TimelinesCounterTableName:
    Description: Name of dynamodb used by application to access the key-value store of CounterTable
    Value: !Ref TimelinesCounterTable
  TimelinesCounterTableArn:
    Description: ARN Dynamo Name used by application to access the key-value store of CounterTable
    Value: !Sub '${TimelinesCounterTable.Arn}'


  # Lambda functions
  WebhookEventManagerLambdaName:
    Value: !Sub "${ProjectName}-webhookEventManagerLambda"


  # Webhook Step Manager DLQ
  WebhookEventManagerDLQName:
    Value: !GetAtt WebhookEventManagerDLQ.Outputs.QueueName
    Description: pn-delivery-push_webhook_event_manager_DLQ queue name
  WebhookEventManagerDLQURL:
    Value: !GetAtt WebhookEventManagerDLQ.Outputs.QueueURL
    Description: pn-delivery-push_webhook_event_manager_DLQ queue URL
  WebhookEventManagerDLQARN:
    Value: !GetAtt WebhookEventManagerDLQ.Outputs.QueueARN
    Description: pn-delivery-push_webhook_event_manager_DLQ queue ARN
  WebhookEventManagerDLQAlarmARN:
    Value: !GetAtt WebhookEventManagerDLQ.Outputs.SqsDLQAlarmArn
    Description: pn-delivery-push_webhook_event_manager_DLQ alarm ARN


  # Log group exports
  EcsLogGroup:
    Value: !GetAtt PnDeliveryPushLogGroup.Outputs.LogGroupName

  # Lambda functions
  NotificationCancellationActionInsertLambdaName:
    Value: !Sub "${ProjectName}-notificationCancellationActionInsertLambda"

  # NotificationCancellationActionInsertLambdaAlarms DLQ
  NotificationCancellationActionInsertDLQName:
    Value: !GetAtt NotificationCancellationActionInsertDLQ.Outputs.QueueName
    Description: pn-delivery-push-notification-cancellationaction-insert_DLQ queue name
  NotificationCancellationActionInsertDLQURL:
    Value: !GetAtt NotificationCancellationActionInsertDLQ.Outputs.QueueURL
    Description: pn-delivery-push-notification-cancellationaction-insert_DLQ queue URL
  NotificationCancellationActionInsertDLQARN:
    Value: !GetAtt NotificationCancellationActionInsertDLQ.Outputs.QueueARN
    Description: pn-delivery-push-notification-cancellationaction-insert_DLQ queue ARN
  NotificationCancellationActionInsertDLQAlarmARN:
    Value: !GetAtt NotificationCancellationActionInsertDLQ.Outputs.SqsDLQAlarmArn
    Description: pn-delivery-push-notification-cancellationaction-insert_DLQ alarm ARN