AWSTemplateFormatVersion: '2010-09-09'
Description: Actions storage

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: unused

  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  LogRetention:
    Type: Number
    Default: 14

  AlarmSNSTopicArn:
    Type: String

Resources:

  # Legal Facts S3 Storage
  LegalFactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      # No default retention neither legal hold.
      # Can define retention period or legal hold when upload new object or version
      ObjectLockEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - "x-amz-version-id"

  NotificationReworkUpdaterQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_push_to_notification_rework_updater'
        DelaySeconds: 1
        MaxReceiveCount: 3
        VisibilityTimeout: 1800
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        QueueHasAlarm: "true"

  # Failed Paper Notification
  PaperNotificationFailedTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-PaperNotificationFailed'
      AttributeDefinitions:
        - AttributeName: "recipientId"
          AttributeType: "S"
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "recipientId"
          KeyType: "HASH"
        - AttributeName: "iun"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Safe storage table containing request
  DocumentCreationRequestTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-DocumentCreationRequestTable'
      AttributeDefinitions:
        - AttributeName: "key"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "key"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  NotificationReworksTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-NotificationReworks'
      AttributeDefinitions:
        - AttributeName: "iun"
          AttributeType: "S"
        - AttributeName: "reworkId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "iun"
          KeyType: "HASH"
        - AttributeName: "reworkId"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PnDeliveryPushLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-delivery-push'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention

  VersioningGetNotificationLegalFactsLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-versioningGetNotificationLegalFactsLambda"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

  NotificationReworkUpdaterLambdaLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-NotificationReworkUpdaterLambda"
        LogGroupRetention: !Ref LogRetention
        LogGroupPrefix: '/aws/lambda'

Outputs:

  # NotificationReworkUpdaterQueue
  NotificationReworkUpdaterQueueName:
    Value: !GetAtt NotificationReworkUpdaterQueue.Outputs.QueueName
    Description: pn-deliveryPushtoNotificationReworkUpdater queue name
  NotificationReworkUpdaterQueueARN:
    Value: !GetAtt NotificationReworkUpdaterQueue.Outputs.QueueARN
    Description: pn-deliveryPushtoNotificationReworkUpdater queue ARN
  NotificationReworkUpdaterQueueURL:
    Value: !GetAtt NotificationReworkUpdaterQueue.Outputs.QueueURL
    Description: pn-deliveryPushtoNotificationReworkUpdater queue URL

  PaperNotificationFailedDynamoTableName:
    Description: Name of dynamodb table containing unreacheble notifications recipients
    Value: !Ref PaperNotificationFailedTable
  PaperNotificationFailedDynamoTableArn:
    Description: ARN of dynamodb table containing unreacheble notifications recipients
    Value: !Sub '${PaperNotificationFailedTable.Arn}'

  DocumentCreationRequestTableName:
    Description: Name of dynamodb table containing Document creation request to storage
    Value: !Ref DocumentCreationRequestTable
  DocumentCreationRequestTableArn:
    Description: ARN of dynamodb table containing Document creation request to storage
    Value: !Sub '${DocumentCreationRequestTable.Arn}'

  NotificationReworksDynamoTableName:
    Description: Name of dynamodb table containing reworked notifications
    Value: !Ref NotificationReworksTable
  NotificationReworksDynamoTableArn:
    Description: ARN of dynamodb table containing reworked notifications
    Value: !Sub '${NotificationReworksTable.Arn}'

  # Lambda functions
  VersioningGetNotificationLegalFactsLambdaName:
    Value: !Sub "${ProjectName}-versioningGetNotificationLegalFactsLambda"

  # Log group exports
  EcsLogGroup:
    Value: !GetAtt PnDeliveryPushLogGroup.Outputs.LogGroupName

  # Lambda functions
  NotificationReworkUpdaterLambdaName:
    Value: !Sub "${ProjectName}-NotificationReworkUpdaterLambda"
