package it.pagopa.pn.deliverypush.dto.legalfacts;

import lombok.Getter;


@Getter
public enum LegalFactCategoryInt {
    SENDER_ACK("SENDER_ACK"), //LegalFacts generated by PN

    ANALOG_FAILURE_DELIVERY("ANALOG_FAILURE_DELIVERY"), //LegalFacts generated by PN

    DIGITAL_DELIVERY("DIGITAL_DELIVERY"), //LegalFacts generated by PN
    
    RECIPIENT_ACCESS("RECIPIENT_ACCESS"), //LegalFacts generated by PN

    PEC_RECEIPT("PEC_RECEIPT"), //LegalFacts received from externalChannel

    ANALOG_DELIVERY("ANALOG_DELIVERY"); //LegalFacts received from externalChannel

    private final String value;

    LegalFactCategoryInt(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
