logging.config=config/logback-local.xml
server.port=8081

cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
cloud.aws.sqs.endpoint= http://localhost:4566

# Runtime mode
pn.env.runtime=DEVELOPMENT
#pn.env.runtime=PROD