logging.config=config/logback-local.xml
server.port=8081

cors.allowed.domains=http://localhost:8090,http://localhost:8091

pn.delivery-push.delivery-base-url=http://localhost:8080
pn.delivery-push.data-vault-base-url=http://localhost:8084
pn.delivery-push.safe-storage-base-url=http://localhost:8120
pn.delivery-push.mandate-base-url=http://localhost:8086
pn.delivery-push.external-registry-base-url=http://localhost:8087
pn.delivery-push.action-manager-base-url=http://localhost:8090
pn.delivery-push.templates-engine-base-url=http://localhost:8090
pn.delivery-push.timeline-client-base-url=http://localhost:8091
pn.delivery-push.paper-tracker-client-base-url=http://localhost:8090

pn.delivery-push.failed-notification-dao.table-name=PaperNotificationFailed
pn.delivery-push.document-creation-request-dao.table-name=DocumentCreationRequest
pn.delivery-push.notification-reworks-dao.table-name=NotificationReworks

pn.delivery-push.document-number-of-pages-tag-key=document_number_of_pages

cloud.aws.credentials.profile-name=${PN_AWS_PROFILE_NAME:default}
cloud.aws.region.static= us-east-1
cloud.aws.sqs.endpoint= http://localhost:4566

# Runtime mode
pn.env.runtime=DEVELOPMENT
#pn.env.runtime=PROD

# Technology activation
pn.middleware.init.kafka=false
pn.middleware.init.aws=true

# AWS specific configurations
aws.bucketName=local-doc-bucket
aws.region-code=us-east-1
aws.profile-name=${PN_AWS_PROFILE_NAME:default}
aws.endpoint-url=http://localhost:4566

cert.clientCertificatePem=${CLIENT_CERTIFICATE_PEM:}
cert.clientKeyPem=${CLIENT_KEY_PEM:}
cert.serverCertificatesPem=${SERVER_CERTIFICATES_PEM:}

pn.delivery-push.pago-pa-notification-base-cost=100
pn.delivery-push.pago-pa-notification-fee=100
pn.delivery-push.pago-pa-notification-vat=22

pn.delivery-push.notification-rework-enabled=true
pn.delivery-push.restart-attempt-enabled=true