package it.pagopa.pn.deliverypush.exceptions;

import it.pagopa.pn.commons.exceptions.PnExceptionsCodes;

public class PnDeliveryPushExceptionCodes extends PnExceptionsCodes {

    // raccolgo qui tutti i codici di errore di delivery push
    public static final String ERROR_CODE_DELIVERYPUSH_NOTFOUND = "PN_DELIVERYPUSH_NOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_GETFILEERROR = "PN_DELIVERYPUSH_GETFILEERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_UPLOADFILEERROR = "PN_DELIVERYPUSH_UPLOADFILEERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_UPDATEMETAFILEERROR = "PN_DELIVERYPUSH_UPDATEMETAFILEERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_ERRORCOMPUTECHECKSUM = "PN_DELIVERYPUSH_ERRORCOMPUTECHECKSUM";
    public static final String ERROR_CODE_DELIVERYPUSH_ATTACHMENTCHANGESTATUSFAILED = "PN_DELIVERYPUSH_ATTACHMENTCHANGESTATUSFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_STATUSNOTFOUND = "PN_DELIVERYPUSH_STATUSNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_ROOTIDNOTFOUND = "PN_DELIVERYPUSH_ROOTIDNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_AUDITLOGFAILED = "PN_DELIVERYPUSH_AUDITLOGFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_NO_RECIPIENT_IN_NOTIFICATION = "PN_DELIVERYPUSH_NORECIPIENTINNOTIFICATION";
    public static final String ERROR_CODE_DELIVERYPUSH_NOTIFICATIONFAILED = "PN_DELIVERYPUSH_NOTIFICATIONFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_DUPLICATED_ITEMD = "PN_DELIVERYPUSH_DUPLICATED_ITEM";
    public static final String ERROR_CODE_DELIVERYPUSH_READ_FILE_ERROR = "PN_DELIVERYPUSH_READ_FILE_ERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_FILE_NOT_FOUND = "PN_DELIVERYPUSH_FILE_NOT_FOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_NOTIFICATIONCANCELLED = "PN_DELIVERYPUSH_NOTIFICATION_CANCELLED";
    public static final String ERROR_CODE_DELIVERYPUSH_FILE_GONE = "PN_DELIVERYPUSH_FILE_GONE";
    public static final String ERROR_CODE_DELIVERYPUSH_NOTIFICATIONREWORK_CONFLICT  = "PN_DELIVERYPUSH_NOTIFICATIONREWORK_CONFLICT";
    public static final String ERROR_CODE_UPDATE_ON_RESTART  = "ERROR_CODE_UPDATE_ON_RESTART";

    public static final String ERROR_CODE_DELIVERY_PUSH_NOTIFICATION_NOT_ACCEPTED = "PN_DELIVERY_PUSH_NOTIFICATION_NOT_ACCEPTED";

    public static final String ERROR_CODE_DELIVERYPUSH_ACTION_CONFLICT = "PN_ACTIONMANAGER_ERROR_CODE_ACTION_CONFLICT";
    public static final String ERROR_CODE_DELIVERYPUSH_SERVICE_NOT_IMPLEMENTED = "PN_DELIVERYPUSH_SERVICE_NOT_IMPLEMENTED";
    public static final String ERROR_CODE_DELIVERYPUSH_ERROR_INVOKING_TRACKER = "ERROR_CODE_DELIVERYPUSH_ERROR_INVOKING_TRACKER";
    public static final String ERROR_DESCRIPTION_DELIVERYPUSH_ERROR_FILE_NOT_FOUND = "ERROR_DESCRIPTION_DELIVERYPUSH_ERROR_FILE_NOT_FOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_TIMELINEELEMENTNOTPRESENT = "PN_TIMELINESERVICE_TIMELINEELEMENTNOTPRESENT";

}
