package it.pagopa.pn.deliverypush.exceptions;

import it.pagopa.pn.commons.exceptions.PnExceptionsCodes;

public class PnDeliveryPushExceptionCodes extends PnExceptionsCodes {

    // raccolgo qui tutti i codici di errore di delivery push
    public static final String ERROR_CODE_DELIVERYPUSH_NOTFOUND = "PN_DELIVERYPUSH_NOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_GETFILEERROR = "PN_DELIVERYPUSH_GETFILEERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_UPLOADFILEERROR = "PN_DELIVERYPUSH_UPLOADFILEERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_UPDATEMETAFILEERROR = "PN_DELIVERYPUSH_UPDATEMETAFILEERROR";
    public static final String ERROR_CODE_DELIVERYPUSH_ERRORCOMPUTECHECKSUM = "PN_DELIVERYPUSH_ERRORCOMPUTECHECKSUM";
    public static final String ERROR_CODE_DELIVERYPUSH_ATTACHMENTCHANGESTATUSFAILED = "PN_DELIVERYPUSH_ATTACHMENTCHANGESTATUSFAILED";
    public static final String ERROR_CODE_DELIVERYPUSH_INVALIDEVENTCODE = "PN_DELIVERYPUSH_INVALIDEVENTCODE";
    public static final String ERROR_CODE_DELIVERYPUSH_INVALIDATTEMPT = "PN_DELIVERYPUSH_INVALIDATTEMPT";

    public static final String ERROR_CODE_DELIVERYPUSH_INVALIDADDRESSSOURCE = "PN_DELIVERYPUSH_INVALIDADDRESSSOURCE";
    public static final String ERROR_CODE_DELIVERYPUSH_SENDDIGITALTIMELINEEVENTNOTFOUND = "PN_DELIVERYPUSH_SENDDIGITALTIMELINEEVENTNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_DIGITALPROGRESSTIMELINEEVENTNOTFOUND = "PN_DELIVERYPUSH_DIGITALPROGRESSTIMELINEEVENTNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_SCHEDULEDDIGITALTIMELINEEVENTNOTFOUND = "PN_DELIVERYPUSH_SCHEDULEDDIGITALTIMELINEEVENTNOTFOUND";
    public static final String ERROR_CODE_DELIVERYPUSH_LASTADDRESSATTEMPTNOTFOUND = "PN_DELIVERYPUSH_LASTADDRESSATTEMPTNOTFOUND";


    public static final String ERROR_CODE_WEBHOOK_UPDATEEVENTSTREAM = "PN_WEBHOOK_UPDATEEVENTSTREAM";
    public static final String ERROR_CODE_WEBHOOK_CONSUMEEVENTSTREAM = "PN_WEBHOOK_CONSUMEEVENTSTREAM";

    public static final String ERROR_CODE_INVALID_RECEIVED_PAPER_STATUS = "ERROR_CODE_INVALID_RECEIVED_PAPER_STATUS";

    public static final String ERROR_CODE_STATUS_NOT_FOUND = "ERROR_CODE_STATUS_NOT_FOUND";

    public static final String ERROR_CODE_AAR_PDF_NOT_FOUND = "ERROR_CODE_AAR_PDF_NOT_FOUND";

    public static final String ERROR_CODE_FEEDBACK_NOT_FOUND = "ERROR_CODE_FEEDBACK_NOT_FOUND";

    public static final String ERROR_CODE_TIMELINE_NOT_FOUND = "ERROR_CODE_TIMELINE_NOT_FOUND";

    public static final String ERROR_CODE_SEND_COURTESY_MESSAGE = "ERROR_CODE_SEND_COURTESY_MESSAGE";

    public static final String ERROR_CODE_NOTIFICATION_RECIPIENT_NOT_FOUND = "ERROR_CODE_NOTIFICATION_RECIPIENT_NOT_FOUND";

    public static final String ERROR_CODE_LEGAL_UPDATE_EXCEPTION = "ERROR_CODE_LEGAL_UPDATE_EXCEPTION";

    public static final String ERROR_CODE_INVALID_EVENT = "ERROR_CODE_INVALID_EVENT";

    public static final String ERROR_CODE_CONTACT_PHASE_NOT_FOUND = "ERROR_CODE_CONTACT_PHASE_NOT_FOUND";

    public static final String ERROR_CODE_DELIVERY_NOT_FOUND = "ERROR_CODE_DELIVERY_NOT_FOUND";

    public static final String ERROR_CODE_UPDATE_NOTIFICATION_FAILED = "ERROR_CODE_UPDATE_NOTIFICATION_FAILED";

    public static final String ERROR_CODE_TIMELINE_CONFIDENTIAL_FAILED = "ERROR_CODE_TIMELINE_CONFIDENTIAL_FAILED";

    public static final String ERROR_CODE_TAX_ID_NOTICE_CODE_FAILED = "ERROR_CODE_TAX_ID_NOTICE_CODE_FAILED";

    public static final String ERROR_CODE_AUDIT_LOG_FAILED = "ERROR_CODE_AUDIT_LOG_FAILED";

    public static final String ERROR_CODE_SAVE_LEGAL_FACTS_FAILED = "ERROR_CODE_SAVE_LEGAL_FACTS_FAILED";

    public static final String ERROR_CODE_STATUS_UPDATE_FAILED = "ERROR_CODE_STATUS_UPDATE_FAILED";

    public static final String ERROR_CODE_ADD_TIMELINE_FAILED = "ERROR_CODE_ADD_TIMELINE_FAILED";

    public static final String ERROR_CODE_CHANNEL_TYPE_NOT_SUPPORTED = "ERROR_CODE_CHANNEL_TYPE_NOT_SUPPORTED";

    public static final String ERROR_CODE_SEND_PEC_NOTIFICATION_FAILED = "ERROR_CODE_SEND_PEC_NOTIFICATION_FAILED";

    public static final String ERROR_CODE_SEND_SMS_NOTIFICATION_FAILED = "ERROR_CODE_SEND_SMS_NOTIFICATION_FAILED";

    public static final String ERROR_CODE_SEND_EMAIL_NOTIFICATION_FAILED = "ERROR_CODE_SEND_EMAIL_NOTIFICATION_FAILED";

    public static final String ERROR_CODE_HANDLE_EVENT_FAILED = "ERROR_CODE_HANDLE_EVENT_FAILED";

    public static final String ERROR_CODE_SEND_IO_MESSAGE_FAILED = "ERROR_CODE_SEND_IO_MESSAGE_FAILED";

    public static final String ERROR_CODE_EVENT_TYPE_NOT_SUPPORTED = "ERROR_CODE_EVENT_TYPE_NOT_SUPPORTED";

    public static final String ERROR_CODE_ACTION_TYPE_NOT_SUPPORTED = "ERROR_CODE_ACTION_TYPE_NOT_SUPPORTED";

    public static final String ERROR_CODE_ACTION_EXCEPTION = "ERROR_CODE_ACTION_EXCEPTION";

    public static final String ERROR_CODE_TIMELINE_ELEMENT_FAILED = "ERROR_CODE_TIMELINE_ELEMENT_FAILED";

    public static final String ERROR_CODE_SAVE_NOTIFICATION_FAILED = "ERROR_CODE_SAVE_NOTIFICATION_FAILED";

    public static final String ERROR_CODE_NOTIFICATION_STATUS_FAILED = "ERROR_CODE_NOTIFICATION_STATUS_FAILED";

    public static final String ERROR_CODE_JSON_EXCEPTION = "ERROR_CODE_JSON_EXCEPTION";
    
    public static final String ERROR_CODE_WEBHOOK_EVENT_FAILED= "ERROR_CODE_WEBHOOK_EVENT_FAILED";
}
